language: cpp
dist: trusty
install: sudo add-apt-repository -y ppa:beineri/opt-qt57-trusty && sudo apt-get update && sudo apt-get install -y qt57charts-no-lgpl qt57serialport qt57tools qt57base build-essential libfontconfig1 
compiler: gcc
script: QTDIR="/opt/qt57" && PATH="$QTDIR/bin:$PATH" && qt57-env.sh && qmake strawhat.pro && make
